remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have oneÏ
title: error-x
description: A simple and consistent error handling library for TypeScript applications
